apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 2
  selector:
    app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: my-spring-app
          image: "image-registry.openshift-image-registry.svc:5000/my-project/my-spring-app"
          ports:
            - containerPort: 8080
